"""empty message

Revision ID: 512e3bdb664d
Revises: 
Create Date: 2020-02-18 19:09:25.423467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '512e3bdb664d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Binomes',
    sa.Column('massar1', sa.String(length=30), nullable=False),
    sa.Column('nom1', sa.String(length=30), nullable=False),
    sa.Column('prenom1', sa.String(length=30), nullable=False),
    sa.Column('nom2', sa.String(length=30), nullable=True),
    sa.Column('prenom2', sa.String(length=30), nullable=True),
    sa.Column('massar2', sa.String(length=30), nullable=True),
    sa.Column('password', sa.String(length=50), nullable=False),
    sa.Column('filiere', sa.String(length=4), nullable=False),
    sa.Column('hasPFE', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('massar1'),
    sa.UniqueConstraint('massar2')
    )
    op.create_table('PFE',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Filiere', sa.String(length=4), nullable=False),
    sa.Column('titre', sa.String(length=100), nullable=False),
    sa.Column('taken', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('titre')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('PFE')
    op.drop_table('Binomes')
    # ### end Alembic commands ###
